apiVersion: kubedb.com/v1alpha2
kind: Cassandra
metadata:
  name: cassandra-sample
  namespace: demo
spec:
  version: 5.0.3
  topology:
    rack:
      - name: myrack
        replicas: 2
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        podTemplate:
          spec:
            containers:
              - name: cassandra
                resources:
                  limits:
                    memory: 4Gi
                    cpu: 4
                  requests:
                    memory: 1Gi
                    cpu: 1
            securityContext:
              runAsUser: 999
              fsGroup: 999
  deletionPolicy: WipeOut
