apiVersion: kubedb.com/v1
kind: Memcached
metadata:
  name: memcd-quickstart
  namespace: demo
spec:
  replicas: 1
  version: "1.6.22"
  deletionPolicy: WipeOut
  podTemplate:
    spec:
      securityContext:
        fsGroup: 1000670000
      containers:
        - name: memcached
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 0
            runAsNonRoot: true
            runAsUser: 1000670000
            seccompProfile:
              type: RuntimeDefault
  monitor:
  agent: prometheus.io/operator
  prometheus:
    serviceMonitor:
      labels:
        release: prometheus
    exporter:
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 512Mi
          cpu: 250m
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsGroup: 0
      runAsNonRoot: true
      runAsUser: 1000670000
      seccompProfile:
        type: RuntimeDefault

