apiVersion: kubedb.com/v1alpha2
kind: Milvus
metadata:
  name: milvus-cluster
  namespace: demo
spec:
  version: "2.6.11"
  objectStorage:
    configSecret:
      name: "my-release-minio"
  topology:
    mode: Distributed
    distributed:
      mixcoord:
        replicas: 2
      proxy:
        replicas: 2
        podTemplate:
          spec:
            containers:
              - name: milvus
                resources:
                  requests:
                    cpu: "156m"
                    memory: "512Mi"
                  limits:
                    memory: "1Gi"
      streamingnode:
        replicas: 3
        storageType: Durable
        storage:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 10Gi





