apiVersion: kubedb.com/v1alpha2
kind: Solr
metadata:
  name: solr
  namespace: demo
spec:
  version: 9.4.1
  deletionPolicy: Halt
  zookeeperRef:
    name: zookeeper
    namespace: demo
  topology:
    overseer:
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
        storageClassName: longhorn
    data:
      replicas: 1
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: longhorn
    coordinator:
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 700Mi
        storageClassName: longhorn
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s