apiVersion: kubedb.com/v1alpha2
kind: Druid
metadata:
  name: druid-sample
  namespace: druid
spec:
  version: 28.0.1
  storageType: Ephemeral
  #  configSecret:
  #    name: custom-config
  deepStorage:
    type: s3
    configSecret:
      name: deep-storage-config
  metadataStorage:
    name: mysql-cluster
    namespace: druid
    createTables: true
  zookeeperRef:
    name: zk-cluster
    namespace: druid
  topology:
    coordinators:
      replicas: 1
    overlords:
      replicas: 1
    brokers:
      podTemplate:
        spec:
          nodeSelector:
            app: kubedb
            instance: druid
            component: druid-database
          tolerations:
            - effect: NoSchedule
              key: app
              operator: Equal
              value: kubedb
            - effect: NoSchedule
              key: instance
              operator: Equal
              value: druid
            - effect: NoSchedule
              key: component
              operator: Equal
              value: druid-database
            - effect: NoSchedule
              key: nodepool_type
              operator: Equal
              value: n2-standard-2
          containers:
            - name: druid
              resources:
                requests:
                  cpu: 700m
                  memory: "1200Mi"
      replicas: 1
    historicals:
      replicas: 1
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
#        storageClassName: standard
    middleManagers:
      replicas: 1
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
#        storageClassName: standard
    routers:
      replicas: 1
  serviceTemplates:
  - alias: primary
    spec:
      type: LoadBalancer
