apiVersion: kubedb.com/v1alpha2
kind: ZooKeeper
metadata:
  name: zk-cluster
  namespace: druid
spec:
  version: 3.8.3
  replicas: 3
  storage:
    resources:
      requests:
        storage: "100Mi"
    #    storageClassName: standard
    accessModes:
      - ReadWriteOnce
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer
  terminationPolicy: WipeOut