apiVersion: kubedb.com/v1alpha2
kind: ZooKeeper
metadata:
  name: zookeeper-prod
  namespace: zookeeper
spec:
  podTemplate:
    spec:
      nodeSelector:
        instance: zookeeper
      tolerations:
        - effect: NoSchedule
          key: instance
          operator: Equal
          value: zookeeper
      containers:
        - name: zookeeper
          resources:
            requests:
              cpu: 700m
              memory: "1200Mi"
  version: 3.8.3
  replicas: 3
  storage:
    resources:
      requests:
        storage: "100Mi"
    storageClassName: standard-rwo
    accessModes:
      - ReadWriteOnce
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer
  terminationPolicy: Halt