apiVersion: kubedb.com/v1
kind: MySQL
metadata:
  name: mysql-cluster
  namespace: druid
spec:
  version: "8.0.35"
  topology:
    mode: GroupReplication
  replicas: 3
  podTemplate:
    containers:
      - name: mysql
        spec:
          resources:
            requests:
              cpu: 400m
              memory: 700Mi
  storage:
    #    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  init:
    script:
      configMap:
        name: my-init-script