apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis-sentinel
  namespace: demo
spec:
  version: 6.2.14
  replicas: 3
  sentinelRef:
    name: sentinel
    namespace: demo
  mode: Sentinel
  disableAuth: true
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 10Gi
    storageClassName: "default"
    accessModes:
      - ReadWriteOnce
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
