apiVersion: kubedb.com/v1alpha2
kind: RedisSentinel
metadata:
  name: sentinel
  namespace: demo
spec:
  version: 6.2.14
  replicas: 3
  disableAuth: true
  storageType: Durable
  podTemplate:
    spec:
      nodeSelector:
        app: kubedb
        instance: sentinel
        component: sentinel-database
      tolerations:
        - effect: NoSchedule
          key: app
          operator: Equal
          value: kubedb
        - effect: NoSchedule
          key: instance
          operator: Equal
          value: sentinel
        - effect: NoSchedule
          key: component
          operator: Equal
          value: sentinel-database
        - effect: NoSchedule
          key: nodepool_type
          operator: Equal
          value: n2-standard-2
      resources:
        requests:
          cpu: "400m"
          memory: "600Mi"
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "default"
    accessModes:
      - ReadWriteOnce
  terminationPolicy: WipeOut
