apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: postgres
  namespace: demo
spec:
  deletionPolicy: WipeOut
  configSecret:
    name: user-conf
  version: "13.13"
  replicas: 3
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s