apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mongodb
  namespace: demo
spec:
  version: "4.4.26"
  deletionPolicy: WipeOut
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s