apiVersion: kubedb.com/v1alpha2
kind: Solr
metadata:
  name: solr-combined
  namespace: solr
spec:
  version: 9.4.1
  terminationPolicy: Delete
  replicas: 2
  zookeeperRef:
    name: zk-com
    namespace: zookeeper
  podTemplate:
    spec:
      nodeSelector:
        app: kubedb
        instance: solr
        component: solr-database
      tolerations:
        - effect: NoSchedule
          key: app
          operator: Equal
          value: kubedb
        - effect: NoSchedule
          key: instance
          operator: Equal
          value: solr
        - effect: NoSchedule
          key: component
          operator: Equal
          value: solr-database
        - effect: NoSchedule
          key: nodepool_type
          operator: Equal
          value: n2-standard-2
      containers:
        - name: solr
          resources:
            requests:
              "cpu": 400m
              "memory": "1200Mi"
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: standard-rwo
  serviceTemplates:
  - alias: primary
    spec:
      type: LoadBalancer