apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lVRkhmbXgrbGxyNnJLN2c0eTdwUVBWYWt2cDFNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lURU9NQXdHQTFVRUF3d0ZiWE56Y1d3eER6QU5CZ05WQkFvTUJtdDFZbVZrWWpBZUZ3MHlOREE1TVRndwpPVEkzTVRKYUZ3MHlOVEE1TVRnd09USTNNVEphTUNFeERqQU1CZ05WQkFNTUJXMXpjM0ZzTVE4d0RRWURWUVFLCkRBWnJkV0psWkdJd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUMyYk9nTi8vTlMKYkVma0gvWEJYWHJFMVl3T3g0U0dSTnhiM0hXZDdHT3FRV2NxMjFLdzYrTVVFdExwTXI5b0Y4ekRNaDUyS0FjbQpZUkRvVHJHMFl1VUhOZDN2UWlmUWN0NmtKc0Y4cXlkYkJYNVFac0dMbzFkdHR2UER0aXNxVGtLL2prQy9TQkg2ClZkVkVtWFppTVJ0VGsvQnBlNGUyVk12MzZMWncxTVltM1hoaXNlN0orQWh4NHcvNU5iMUNFdjFaWHVIRzhDUEcKTDE2Y3JqZU1FNUdBVTR1VFFnb09RL1k5amp6ZHVOREVLQndMeXhuZUV4MUdWUkYvaTFlQ040SHAwZVVWVWIyNgppU2NObVdCQ1NnYXVFRk1qVlRSMFo3QnIyZ3ZWVWo0R1crL2JJQjEvamsreDRGa041TzFIU1IxaGFFcWxSTDJGCkwrR1NMNnRyNzZtTkFnTUJBQUdqVXpCUk1CMEdBMVVkRGdRV0JCUlNpekIyaXpWb0h2bVg5YURXbTZ2cmtFMHoKK0RBZkJnTlZIU01FR0RBV2dCUlNpekIyaXpWb0h2bVg5YURXbTZ2cmtFMHorREFQQmdOVkhSTUJBZjhFQlRBRApBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCRG5NMU50aGVWRWczeDFGWmI2TkhoaDcwelJSNDVaV0RxCjlZc2E3YW9INmI5ZzFLRDFFcUNlZkt1ZjdEQzFtRUFVeGh1aDE4bmUrZHFGeERjL2cwWjlDWkN3TmsrbEdZTzAKdndWSUlOSG9sMUlqUG5tTFFZcWFUS282VlFPRDNNZ1N3Z2J0alYzdmt6TmlsZC8zR1dBbGFQbVhXMVRNQXFIWAp5SzMwMFA2Znc5bUR4WWEvQ3A4KzFaV1FmTFZYQmdsaHNhSlpOOE1sQ3ZkQm1IMzdaYmNRelBleGFWMGhYT3UwCkNMT1drU0pQbkhrOFRUcVp4WmNsVHk2d3REblA4TkxMTlZycnlrN09lYkFvZ3VDSGhYV0RYR1MrZGlsem9CQlIKL3U4cUFvTjMzQkxDTUtQNHZYYXphWTZST3JhL2lwMGRyeWJNRjZ4NFI0T3FXS1I3cnZUTwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzJiT2dOLy9OU2JFZmsKSC9YQlhYckUxWXdPeDRTR1JOeGIzSFdkN0dPcVFXY3EyMUt3NitNVUV0THBNcjlvRjh6RE1oNTJLQWNtWVJEbwpUckcwWXVVSE5kM3ZRaWZRY3Q2a0pzRjhxeWRiQlg1UVpzR0xvMWR0dHZQRHRpc3FUa0svamtDL1NCSDZWZFZFCm1YWmlNUnRUay9CcGU0ZTJWTXYzNkxadzFNWW0zWGhpc2U3SitBaHg0dy81TmIxQ0V2MVpYdUhHOENQR0wxNmMKcmplTUU1R0FVNHVUUWdvT1EvWTlqanpkdU5ERUtCd0x5eG5lRXgxR1ZSRi9pMWVDTjRIcDBlVVZVYjI2aVNjTgptV0JDU2dhdUVGTWpWVFIwWjdCcjJndlZVajRHVysvYklCMS9qayt4NEZrTjVPMUhTUjFoYUVxbFJMMkZMK0dTCkw2dHI3Nm1OQWdNQkFBRUNnZ0VBRmZYM1c1UVg1VEMrMk5JV0lqQ1FNbmpvc3ZERzNla1ZSQU8rcndQQm5jSGcKMnhKckdueFRLbHYzd3ZZR2Y4LzVxUGYwSGRKRXhoU0NWZ3ovTEpHSk03eUMycVl5cDgva1NJdVgyRnU4VWFOUQpLUHF0eXhNZlY4aGlBUW9CbVVheGwyRFhINC9jQmpCbUM2dVR5azlTRkZZblozTmxDNGlhdzEzaTlLTlF0V1hZCjRoeUJ3K3RxSEMweHVGNXh3Rm8vL2JxYWNSZnBuczg0Z2xSbitFYndWeUw2cWF1Q09DQ1lKR1I3NnlJRU1HN3gKVGJDb0NKSC9wOStYeDBNVzVLZnVIM2NlRnZmeElQS0t5VkswZ2JZSCtnV21mVUQ0UnYvME56UFRIOHR6UjFLOApTZTNCcDJ6T3dTMGJ3RFNJU29xM2xoK0Y5NGluM0c5RkZSN0ROanZzTVFLQmdRRGdnVmwvL1RVb2R5c2pESHNXCmhmcTNmZG5ldG5OY3drMG1JQWI5Y3JCc2hLRTZNdVk2SGRlNWR2b0NRZjlHRWI5U1c4S3F0UGpIQ2plblZoc0kKKzRtVDVVcjdWVnVDNGNTZkJTNjFFNG0yZENId1Ezb1JtQkxQT1BiQzEycC85aWNTbFA2UlAxZnJsaklObWNmcwpZT3RhM0pEM0hSOXYrSTRZY0hqTGZ0WU55UUtCZ1FEUUJGZ3BONU1vclRUQnpJMG5zTUVPcGNoRmd3enI2dlBRClB0ZVk5SnczanEwdWJNTzNCOTluVEtyRk5Qck5CY3dCdUtwY0V0dk5SbkVMZytSdkRDVUJiTkxyMHVETGNJR1IKSTVONlVZQ0RuMXd3eHd6NXYvSzNoNzBSR0k4Ym1rSENSWS9OMnUwN0UvSkdyR3IrSy92TGFqYTh2a1ByMUNTKworcDZMUk5vUHBRS0JnUURGbC9MKzNBdjZWcEJINDhjOTlxUEk5ZUpZeTNwVGpNdThIM29uZmRiYlhBeFBIZGRXCkZVZjErMHBsekZKeUNGSzhtUGlIcUlwQkhMUUkrcGNHMitTbG42elQ4cmQ5UlZuNW4rVVJDR1l2aUowS1MwbFgKek9IWk1zaTBpa1k0NDV4V0ZYN010ZFNiQy9GMzJQNkdCSE9BNEJwUzlIWGo1ZjZpY2ZOUEg0NGtTUUtCZ0NQNQpmRjIwZE1qR0c2ZWdmcERzcXBhajZSek1hMEdwb256VFFXbjhjNy9QOXZkZWJBS05ZLzl6Yk4wcUttMm1vUDl6Ck5sTXlGNzFLZjJaa2F1OGhoSXpZaXltcGtLTGVWQ29Mb3dlMmJLbFd1QlRmZDhrQmZ6SnFVVEpSc3Y0dEVVNU4KeFc3dWU3U0o0STZFWndTS0NzUEZISzVMb1dkNWl0bFVjbkxYZDNiWkFvR0FCdWZoMDJYRFNSYWZJTld4eUF4Lwo0VDVlQ1NrdE5EUW45Yk96bkNKVUFDcFQzeTAyYWxDZXF6ckF6OXdQSVBoMUp1Y040WkZUU3dNY3Y4OWpiaHFUCit6YXl5Z21DSjJmOVE4TkpVTEVaZ3VwTzJvUFVyRC9CLzN1aHJmMGNuQnVMdmsydnFQTW1CYXVEKzJadE9HK2sKYy9mZWRMY3pqOUhnR0QyOS9KbEk5eTQ9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: mssqlserver-ca
  namespace: demo
type: kubernetes.io/tls

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mssqlserver-ca-issuer
  namespace: demo
spec:
  ca:
    secretName: mssqlserver-ca

---

apiVersion: kubedb.com/v1alpha2
kind: MSSQLServer
metadata:
  name: mssqlserver
  namespace: demo
spec:
  version: "2022-cu12"
  replicas: 3
  topology:
    mode: AvailabilityGroup
    availabilityGroup:
      databases:
        - agdb1
        - agdb2
  internalAuth:
    endpointCert:
      issuerRef:
        apiGroup: cert-manager.io
        name: mssqlserver-ca-issuer
        kind: Issuer
  tls:
    issuerRef:
      name: mssqlserver-ca-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
    clientTLS: false
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        port: 9399
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi