apiVersion: kubedb.com/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: demo
spec:
  version: opensearch-2.8.0
  enableSSL: true
  replicas: 2
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s