apiVersion: kubedb.com/v1alpha2
kind: RabbitMQ
metadata:
  name: rabbit-dev
  namespace: demo
spec:
  version: "3.12.12"
  replicas: 3
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut