apiVersion: kubedb.com/v1
kind: PerconaXtraDB
metadata:
  name: perconaxtradb
  namespace: demo
spec:
  version: "8.0.26"
  deletionPolicy: WipeOut
  storage:
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s