apiVersion: kubedb.com/v1alpha2
kind: Singlestore
metadata:
  name: singlestore-sample
  namespace: demo
spec:
  version: "8.1.32"
  topology:
    aggregator:
      replicas: 3
      storage:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    leaf:
      replicas: 2
      storage:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  licenseSecret:
    name: license-secret
  #  authSecret:
  #    name: given-secret
  storageType: Durable
  terminationPolicy: Halt
