apiVersion: kubedb.com/v1alpha2
kind: Neo4j
metadata:
  name: neo4j-tls
  namespace: demo
spec:
  deletionPolicy: WipeOut
  replicas: 3
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  storageType: Durable
  tls:
    bolt:
      mode: TLS
    cluster:
      mode: mTLS
    http:
      mode: TLS
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: neo4j-ca-issuer
  version: 2025.11.2
