apiVersion: kafka.kubedb.com/v1alpha1
kind: ConnectCluster
metadata:
  name: connect-cluster
  namespace: demo
spec:
  version: 3.6.0
  connectorPlugins:
    - gcs-0.13.0
    - mongodb-1.11.0
    - mysql-2.4.2.final
    - postgres-2.4.2.final
    - s3-2.15.0
  kafkaRef:
    name: kafka-prod
    namespace: demo
  replicas: 2
  podTemplate:
    spec:
      nodeSelector:
        app: kubedb
        instance: kafka
        component: kafka-database
      tolerations:
        - effect: NoSchedule
          key: app
          operator: Equal
          value: kubedb
        - effect: NoSchedule
          key: instance
          operator: Equal
          value: kafka
        - effect: NoSchedule
          key: component
          operator: Equal
          value: kafka-database
        - effect: NoSchedule
          key: nodepool_type
          operator: Equal
          value: n2-standard-2
      containers:
        - name: connect-cluster
          resources:
            requests:
              "cpu": 400m
              "memory": "1200Mi"
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer
  terminationPolicy: WipeOut
