apiVersion: kubedb.com/v1alpha2
kind: RabbitMQ
metadata:
  name: rabbitmq
  namespace: rabbit
spec:
  version: "3.12.12"
  replicas: 3
  # authSecret:
  #   name: rabbit-user  # reference to a secret containing user (admin) credentials
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
#    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut  # DoNotTerminate(blocks deletion), Halt( retains pvc,secret), Delete (retains secret)
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s