apiVersion: kubedb.com/v1alpha2
kind: Oracle
metadata:
  name: oracle-dataguard
  namespace: demo
spec:
  dataGuard:
    applyLagThreshold: 0
    fastStartFailover:
      fastStartFailoverThreshold: 15
    protectionMode: MaximumProtection
    standbyType: PHYSICAL
    syncMode: SYNC
    transportLagThreshold: 0
  deletionPolicy: Delete
  edition: enterprise
  mode: DataGuard
  podTemplate:
    spec:
      containers:
      - name: oracle
        resources:
          limits:
            cpu: "4"
            memory: 10Gi
          requests:
            cpu: "2"
            memory: 5Gi
  replicas: 3
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
  storageType: Durable
  version: oracle-21.3.0