apiVersion: kubedb.com/v1alpha2
kind: Oracle
metadata:
  name: oracle
  namespace: demo
spec:
  version: "21.3.0"
  replicas: 1
  edition: "enterprise"
  mode: "Standalone"
  storage:
     accessModes:
       - ReadWriteOnce
     resources:
       requests:
         storage: 30Gi
