apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: pg
  namespace: pool
spec:
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: standard-rwo
  storageType: Durable
  deletionPolicy: WipeOut
  version: "15.3"