apiVersion: kubedb.com/v1alpha2
kind: Pgpool
metadata:
  name: pgpool-test
  namespace: pool
spec:
  version: "4.5.0"
  replicas: 3
  postgresRef:
    name: ha-postgres
    namespace: demo
  terminationPolicy: WipeOut
  syncUsers: true
  podTemplate:
    spec:
      containers:
        - name: pgpool
          resources:
            requests:
              "cpu": 700m
              "memory": "1400Mi"
  initConfig:
    pgpoolConfig:
      log_statement : on
      log_per_node_statement : on
      sr_check_period : 0
      health_check_period : 0
      backend_clustering_mode : 'streaming_replication'
      num_init_children : 5
      max_pool : 100
      child_life_time : 300
      child_max_connections : 0
      connection_life_time : 0
      client_idle_limit : 0
      connection_cache : on
      load_balance_mode : on
      ssl : on
      failover_on_backend_error : off
      log_min_messages : warning
      statement_level_load_balance: on
      memory_cache_enabled: on
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer
