apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: ha-postgres
  namespace: pool
spec:
  terminationPolicy: WipeOut
  configSecret:
    name: user-conf
  version: "13.13"
  replicas: 3
  storageType: Durable
  storage:
    storageClassName: "standard-rwo"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi