apiVersion: kubedb.com/v1
kind: PgBouncer
metadata:
  name: pgbouncer
  namespace: demo
spec:
  version: "1.18.0"
  replicas: 3
  database:
    syncUsers: true
    databaseName: "postgres"
    databaseRef:
      name: "postgres"
      namespace: demo
  connectionPool:
    port: 5432
    reservePoolSize: 3
  deletionPolicy: Delete
  podTemplate:
    spec:
      containers:
        - name: pgbouncer
          resources:
            limits:
              cpu: .5
              memory: 1Gi
            requests:
              cpu: .5
              memory: 1Gi


