apiVersion: kafka.kubedb.com/v1alpha1
kind: ConnectCluster
metadata:
  name: connectcluster
  namespace: demo
spec:
  version: 3.6.1
  kafkaRef:
    name: kafka
    namespace: demo
  replicas: 2
  terminationPolicy: WipeOut
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
