apiVersion: v1
kind: Secret
metadata:
  name: file-source-config
  namespace: demo
stringData:
  config.properties: |
    connector.class=FileStreamSource
    tasks.max=1
    file=/opt/kafka/config/connect-distributed.properties
    topic=graphana

---
apiVersion: kafka.kubedb.com/v1alpha1
kind: Connector
metadata:
  name: file-source-connector
  namespace: demo
spec:
  configSecret:
    name: file-source-config
  connectClusterRef:
    name: connectcluster
    namespace: demo
  deletionPolicy: WipeOut
