apiVersion: kubedb.com/v1alpha2
kind: FerretDB
metadata:
  name: ferretdb-sample
  namespace: demo
spec:
  version: "1.18.0"
  authSecret:
    externallyManaged: false
  sslMode: disabled
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
  backend:
    externallyManaged: false
  terminationPolicy: WipeOut