apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mongodb-replicaset
  namespace: demo
spec:
  version: "4.4.26"
  replicas: 2
  replicaSet:
    name: rs0
  storage:
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
      exporter:
        args: [ "--compatible-mode" ]
