apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mongodb
  namespace: demo
spec:
  version: 4.4.26
  deletionPolicy: WipeOut
  shardTopology:
    configServer:
      replicas: 2
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
    mongos:
      replicas: 1
    shard:
      replicas: 2
      shards: 2
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
      exporter:
        args: ["--compatible-mode"]