apiVersion: kubedb.com/v1
kind: Redis
metadata:
  name: redis
  namespace: demo
spec:
  disableAuth: true
  version: 7.2.3
  mode: Cluster
  cluster:
    shards: 3
    replicas: 2
  storageType: Durable
  storage:
    resources:
      requests:
        storage: "2Gi"
#    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
  deletionPolicy: WipeOut
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
