apiVersion: kubedb.com/v1
kind: Redis
metadata:
  name: redis-standalone
  namespace: demo
spec:
  version: 7.2.3
  replicas: 1
  disableAuth: true
  storageType: Durable
  storage:
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
