apiVersion: kubedb.com/v1alpha2
kind: Solr
metadata:
  name: solr
  namespace: demo
spec:
  version: 9.4.1
  deletionPolicy: Delete
  replicas: 3
  zookeeperRef:
    name: zk-ensemble
    namespace: demo
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
