apiVersion: v1
kind: Secret
metadata:
  name: gcs-sink-config
  namespace: demo
stringData:
  config.properties: |
    connector.class=io.aiven.kafka.connect.gcs.GcsSinkConnector
    tasks.max=1
    topics=<topics-to-sink>
    gcs.bucket.name=<bucket-name>
    gcs.credentials.json=<gcs-credentials-json>
    key.converter=org.apache.kafka.connect.storage.StringConverter
    value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
    value.converter.schemas.enable=false
    file.compression.type=gzip
    file.name.template={{topic}}-{{partition:padding=true}}-{{start_offset:padding=true}}.gz
---
apiVersion: kafka.kubedb.com/v1alpha1
kind: Connector
metadata:
  name: gcs-sink-connector
  namespace: demo
spec:
  configSecret:
    name: gcs-sink-config
  connectClusterRef:
    name: connect-cluster
    namespace: demo
  deletionPolicy: WipeOut
