apiVersion: v1
kind: Secret
metadata:
  name: mg-source-config
  namespace: demo
stringData:
  config.properties: |
    connector.class=com.mongodb.kafka.connect.MongoSourceConnector
    tasks.max=1
    connection.uri=<MongoDB URI>
    topic.prefix=mongo
    database=test
    collection=source
    poll.max.batch.size=1000
    poll.await.time.ms=5000
    heartbeat.interval.ms=3000
    startup.mode=copy_existing
    publish.full.document.only=true
    key.ignore=true
    value.converter=org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable=false
---
apiVersion: kafka.kubedb.com/v1alpha1
kind: Connector
metadata:
  name: mg-source-connector
  namespace: demo
spec:
  configSecret:
    name: mg-source-config
  connectClusterRef:
    name: connect-cluster
    namespace: demo
  deletionPolicy: WipeOut