apiVersion: kubedb.com/v1alpha2
kind: Solr
metadata:
  name: solr-dev
  namespace: solr
spec:
  version: 9.4.1
  terminationPolicy: Halt
  replicas: 3
  zookeeperRef:
    name: zookeeper-prod
    namespace: zookeeper
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi
    storageClassName: standard-rwo
  podTemplate:
    spec:
      nodeSelector:
        instance: solr
      tolerations:
        - effect: NoSchedule
          key: instance
          operator: Equal
          value: solr
      containers:
        - name: solr
          resources:
            requests:
              cpu: 500m
              memory: "1600Mi"
