apiVersion: kubedb.com/v1alpha2
kind: Solr
metadata:
  name: solr-dev
  namespace: solr
spec:
  version: 9.4.1
  deletionPolicy: Halt
  replicas: 3
  zookeeperRef:
    name: zookeeper-prod
    namespace: zookeeper
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi
#    storageClassName: standard
  podTemplate:
    spec:
      nodeSelector:
        app: kubedb
        instance: solr
        component: solr-database
      tolerations:
        - effect: NoSchedule
          key: app
          operator: Equal
          value: kubedb
        - effect: NoSchedule
          key: instance
          operator: Equal
          value: solr
        - effect: NoSchedule
          key: component
          operator: Equal
          value: solr-database
        - effect: NoSchedule
          key: nodepool_type
          operator: Equal
          value: n2-standard-2
      containers:
        - name: solr
          resources:
            requests:
              cpu: 500m
              memory: "1600Mi"
