apiVersion: kubedb.com/v1alpha2
kind: Kafka
metadata:
  name: kafka-dev
  namespace: demo
spec:
  replicas: 2
  version: 3.6.0
  podTemplate:
    spec:
      nodeSelector:
        app: kubedb
        instance: kafka
        component: kafka-database
      tolerations:
        - effect: NoSchedule
          key: app
          operator: Equal
          value: kubedb
        - effect: NoSchedule
          key: instance
          operator: Equal
          value: kafka
        - effect: NoSchedule
          key: component
          operator: Equal
          value: kafka-database
        - effect: NoSchedule
          key: nodepool_type
          operator: Equal
          value: n2-standard-2
      containers:
        - name: kafka
          resources:
            requests:
              "cpu": 400m
              "memory": "1200Mi"
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
#    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer