apiVersion: kubedb.com/v1alpha2
kind: Kafka
metadata:
  name: kafka-dev
  namespace: demo
spec:
  replicas: 2
  version: 3.6.0
  podTemplate:
    spec:
      nodeSelector:
        instance: kafka
      tolerations:
        - effect: NoSchedule
          key: instance
          operator: Equal
          value: kafka
      containers:
        - name: kafka
          resources:
            requests:
              "cpu": 400m
              "memory": "1200Mi"
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
#    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut