apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis-cluster
  namespace: demo
spec:
  disableAuth: true
  version: 7.2.3
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  storageType: Durable
  storage:
    resources:
      requests:
        storage: "2Gi"
#    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
  podTemplate:
    spec:
      nodeSelector:
        app: kubedb
        instance: redis
        component: redis-database
      tolerations:
        - effect: NoSchedule
          key: app
          operator: Equal
          value: kubedb
        - effect: NoSchedule
          key: instance
          operator: Equal
          value: redis
        - effect: NoSchedule
          key: component
          operator: Equal
          value: redis-database
        - effect: NoSchedule
          key: nodepool_type
          operator: Equal
          value: n2-standard-2
      resources:
        requests:
          cpu: "400m"
          memory: "600Mi"
  terminationPolicy: WipeOut
