apiVersion: kubedb.com/v1alpha2
kind: Hazelcast
metadata:
  name: hazelcast-sample
  namespace: demo
spec:
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      name: self-signed-issuer
      kind: ClusterIssuer
    certificates:
      - alias: server
        subject:
          organizations:
            - kubedb
        dnsNames:
          - localhost
        ipAddresses:
          - "127.0.0.1"
      - alias: client
        subject:
          organizations:
            - kubedb
        dnsNames:
          - localhost
        ipAddresses:
          - "127.0.0.1"
  enableSSL: true
  deletionPolicy: Halt
  licenseSecret:
    name: hz-license-key
  podTemplate:
    spec:
      nodeSelector:
        app: kubedb
        instance: hazelcast
        component: hazelcast-database
      tolerations:
      - effect: NoSchedule
        key: app
        operator: Equal
        value: kubedb
      - effect: NoSchedule
        key: instance
        operator: Equal
        value: hazelcast
      - effect: NoSchedule
        key: component
        operator: Equal
        value: hazelcast-database
      - effect: NoSchedule
        key: nodepool_type
        operator: Equal
        value: n2-standard-2
      containers:
      - name: hazelcast
        resources:
          requests:
            "cpu": 500m
            "memory": "1500Mi"
      initContainers:
      - name: hazelcast-init
        resources:
          requests:
            "cpu": 200m
            "memory": "256Mi"
  replicas: 3
  version: 5.5.2
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: standard

